version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgresdb:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgresdb:
